"""Add Pet models and relationships

Revision ID: 5544d9b54abd
Revises: 96651f74601a
Create Date: 2026-02-25 17:07:30.070588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5544d9b54abd'
down_revision: Union[str, Sequence[str], None] = '96651f74601a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pets_id'), 'pets', ['id'], unique=False)
    op.create_foreign_key(None, 'pets', 'usuarios', ['owner_id'], ['IdUsuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_index(op.f('ix_pets_id'), table_name='pets')
    # ### end Alembic commands ###
